# fly.toml app configuration file generated for learn-pentaho-with-me on 2024-09-29T19:57:48-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'learn-pentaho-with-senthil'
primary_region = 'ewr'

[build]

[[mounts]]
  source = 'pentaho_data'
  destination = '/data'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
